[#ftl output_format="HTML"]
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Blank_Template
	</title><link href="https://test-casa.gluu.info/jans-casa/styles/tachyons.min.css" rel="stylesheet"></head>
<body><a id="i28j">Link</a><section class="bdg-sect"><p class="paragraph f1">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
	  </p></section></body>


</html>